### ISSUE TITLE
Compile with openssl to support credentails feature

### ISSUE THREAD

**Issue by declum** [nathancrjackson/iperf3-windows-builds#1]
Can you please compile with openssl to support credentials feature?

https://github.com/esnet/iperf/discussions/1455

`--username is available only if an OpenSSL library was detected during the iperf3 build. If you built iperf3 yourself search for "ssl" in ./config.log (created when your run ./configure) for a related error/warning messages.

If OpenSSL library library is available, you may try building iperf3 using ./configure --with-openssl=<root of the OpenSSL directory>.`

**Comment by declum** [comment]
I followet

select libssl-devel along with wget in your step.
./configure --with-openssl=/usr

$ cygcheck.exe iperf3
Found: C:\cygwin64\usr\local\bin\iperf3.exe
C:\cygwin64\usr\local\bin\iperf3.exe
  C:\cygwin64\bin\cygcrypto-1.1.dll
    C:\cygwin64\bin\cygwin1.dll
      C:\Windows\system32\KERNEL32.dll
        C:\Windows\system32\ntdll.dll
        C:\Windows\system32\KERNELBASE.dll
    C:\cygwin64\bin\cygz.dll

then when exporing used cygcrypto-1.1.dll, cygwin1.dll, cygz.dll, and iperf3.exe

Server:
  --rsa-private-key-path    path to the RSA private key used to decrypt
                            authentication credentials
  --authorized-users-path   path to the configuration file containing user
                            credentials
Client:
  --username                username for authentication
  --rsa-public-key-path     path to the RSA public key used to encrypt
                            authentication credentials

**Comment by nathancrjackson** [comment]
Hi mate,

Thanks for reaching out. That's a neat feature I didn't even realise iPerf3 had. I'm on holiday at the moment and my Cygwin build environment is currently on my home dev PC (which is powered off with no way to turn on) so I can't troubleshoot this right now but I will take a look into it in a couple of weeks when I am home.

In the meantime I can give some pointers if you have the time to keep looking into it.

> If you built iperf3 yourself search for "ssl" in ./config.log (created when your run ./configure) for a related error/warning messages.

I think this actually gives some solid advice, that log will probably give you a better indicator of what the build process is looking for. With the small amount of looking I've done I'm not able to ascertain if Iperf3 is trying to statically or dynamically link the OpenSSL library. My guess would be dynamic linking for security reason as that way OpenSSL can be upgraded with OS updates even if the app isn't recompiled.

That being said I quickly SSH'd into a 20.04 Ubuntu server I have that I know has a copy of Iperf3 (version 3.7) on it and checked what was linked against it. Maybe looking into the below might help? 

```
# ldd /usr/bin/iperf3
        linux-vdso.so.1 (0x00007ffc5e324000)
        libiperf.so.0 => /lib/x86_64-linux-gnu/libiperf.so.0 (0x00007f3bb1c65000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3bb1a73000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f3bb179c000)
        libsctp.so.1 => /lib/x86_64-linux-gnu/libsctp.so.1 (0x00007f3bb1797000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3bb1ca3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3bb1791000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3bb176e000)
```

Outside of that you can try the shotgun approach which is install every OpenSSL related package in the Cygwin repo, try build it again, see if that works and if it does work your way backwards from there.

If you do figure it out please do update me otherwise I'll look into it more when I get back.

**Comment by nathancrjackson** [comment]
Hi mate,

Apologies for the delay on this one, I had a few things going on.

The short story is that while I am yet to update the guide I have gotten Iperf3 to compile with the authorization options, tested that it is working against a Linux server and updated the releases in this repo.

The long story is that now I am posting this I realise that maybe I misread your second message and you already solved it. Yes, the libssl-devel package is the only extra one that you need but I found that for some reason that adding the --with-openssl flag somehow breaks it. I pulled the configure script apart and found that it already checks /usr if you don't specify the flag and that check works fine. Interestingly you do seem to need to add libssl-devel when installing with wget because I had errors when trying to install it via apt-cyg.

At some point in the future I'll update the guide to include this but in the meantime I will now close this issue.

Thanks for bringing this to my attention.
